name: Build PRs
on:
  pull_request:
    branches:
      - trunk

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'github-actions[bot]' }}
    strategy:
      matrix:
        task: [testDebugUnitTest, assembleRelease]
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up JDK env
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          cache: 'gradle'

      - name: Run ${{ matrix.task }}
        run: ./gradlew --no-daemon --build-cache ${{ matrix.task }}
